# Generated by Django 5.2.8 on 2025-11-30 16:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0003_alter_booking_unique_together_and_more'),
    ]

    operations = [
        migrations.AddConstraint(
            model_name='moviesession',
            constraint=models.UniqueConstraint(fields=('room', 'date_time'), name='uniq_room_datetime'),
        ),
    ]
