# Generated by Django 5.2.8 on 2025-11-30 17:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0004_moviesession_uniq_room_datetime'),
    ]

    operations = [
        migrations.AddField(
            model_name='review',
            name='likes',
            field=models.PositiveIntegerField(default=0),
        ),
    ]
