# Generated by Django 5.2.8 on 2025-11-30 19:12

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0006_reviewlike'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='booking',
            name='seat',
            field=models.CharField(default=0, max_length=8),
            preserve_default=False,
        ),
        migrations.AddConstraint(
            model_name='booking',
            constraint=models.UniqueConstraint(condition=models.Q(('status', 'reserved')), fields=('session', 'seat'), name='uniq_seat_per_session'),
        ),
    ]
