# Generated by Django 5.2.8 on 2025-11-30 19:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0007_booking_seat_booking_uniq_seat_per_session'),
    ]

    operations = [
        migrations.AlterField(
            model_name='booking',
            name='seat',
            field=models.CharField(max_length=3),
        ),
    ]
